
import type { Marks } from './types';

type Subject = {
  key: keyof Marks;
  label: string;
};

export const SUBJECTS_BY_CLASS: Record<string, Subject[]> = {
  Nursery: [
    { key: 'englishOral', label: 'English Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindiOral', label: 'Hindi Oral' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematicsOral', label: 'Mathematics Oral' },
    { key: 'mathematics', label: 'Mathematics' },
  ],
  'L.K.G.': [
    { key: 'englishOral', label: 'English Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindiOral', label: 'Hindi Oral' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematicsOral', label: 'Mathematics Oral' },
    { key: 'mathematics', label: 'Mathematics' },
  ],
  'U.K.G.': [
    { key: 'englishOral', label: 'English Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindiOral', label: 'Hindi Oral' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematicsOral', label: 'Mathematics Oral' },
    { key: 'mathematics', label: 'Mathematics' },
  ],
  '1st': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics' },
    { key: 'science', label: 'Science' },
    { key: 'computer', label: 'Computer' },
  ],
  '2nd': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics' },
    { key: 'science', label: 'Science' },
    { key: 'computer', label: 'Computer' },
  ],
  '3rd': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics' },
    { key: 'science', label: 'Science' },
    { key: 'computer', label: 'Computer' },
  ],
  '4th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics' },
    { key: 'science', label: 'Science' },
    { key: 'computer', label: 'Computer' },
  ],
  '5th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics' },
    { key: 'science', label: 'Science' },
    { key: 'computer', label: 'Computer' },
  ],
  '6th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics' },
    { key: 'science', label: 'Science' },
    { key: 'socialScience', label: 'Social Science' },
    { key: 'computer', label: 'Computer' },
  ],
  '7th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics' },
    { key: 'science', label: 'Science' },
    { key: 'socialScience', label: 'Social Science' },
    { key: 'computer', label: 'Computer' },
  ],
  '8th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics' },
    { key: 'science', label: 'Science' },
    { key: 'socialScience', label: 'Social Science' },
    { key: 'computer', label: 'Computer' },
  ],
  '9th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics/Home Science' },
    { key: 'science', label: 'Science' },
    { key: 'socialScience', label: 'Social Science' },
    { key: 'art', label: 'Art' },
  ],
  '10th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'mathematics', label: 'Mathematics/Home Science' },
    { key: 'science', label: 'Science' },
    { key: 'socialScience', label: 'Social Science' },
    { key: 'art', label: 'Art' },
  ],
  '11th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'physics', label: 'Physics' },
    { key: 'chemistry', label: 'Chemistry' },
    { key: 'biology', label: 'Biology' },
  ],
  '12th': [
    { key: 'oral', label: 'Oral' },
    { key: 'english', label: 'English' },
    { key: 'hindi', label: 'Hindi' },
    { key: 'physics', label: 'Physics' },
    { key: 'chemistry', label: 'Chemistry' },
    { key: 'biology', label: 'Biology' },
  ],
};
